### ISSUE TITLE
notification_config not passing through when using JS SDK

### ISSUE THREAD

**Issue by erkkimon** [speechmatics/speechmatics-js-sdk#60] opened 2024-09-20 10:44 UTC
**Describe the bug**
I might be doing something wrong, but I am able to get notification_config to Speechmatics API using curl while not managing to do it using JS SDK. The both kinds of requests do produce a transcript. However, in the administration panel I can see the notification_config in the payload when using curl but not when using JS SDK. The notification_config seems to be in the typings.

**To Reproduce**
1. Use notification_config like this:
```
{
      input: {
        fetch: { url: url },
      },
      transcription_config: {
        language: spokenLang,
        operating_point: 'enhanced',
        diarization: 'speaker',
        additional_vocab: glossary,
      },
      notification_config: [
        {
          url: 'https://xxxxxxxxxxxxxxxxx',
          method: 'post',
          contents: ['transcript'],
        },
      ],
      ...(spokenLang === 'auto' && {
        language_identification_config: {
          expected_languages: ['en', 'fi', 'sv'],
        },
      }),
      format: 'json-v2' as TranscriptionFormat,
    };
```
2. Send curl request like this:
```
curl -L -X POST "https://asr.api.speechmatics.com/v2/jobs" \
   -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXX" \
   --form config='{
     "type": "transcription",
        "fetch_data": {
	  "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    	},
     "transcription_config": { "language": "auto" },
     "notification_config": [
       {
         "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxx",
         "contents": [ "transcript" ],
         "auth_headers": []
       }
     ]
   }'
```
3. Go to admin panel and see the payload received. Curl request has notification_config while JS SDK request config doesn't.

**Expected behavior**
The notification_config should be sent to Speechmatics also using JS SDK.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Zen Browser (Mozilla Zen 1.0.0-a.37)
 - Speechmatics JS SDK version: 3.1.7

**Additional context**

Request config from Speechmatics panel using curl:
```
{
  "fetch_data": {
    "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  "notification_config": [
    {
      "contents": [
        "transcript"
      ],
      "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "transcription_config": {
    "language": "auto"
  },
  "type": "transcription"
}
```

Request config from Speechmatics panel using JS SDK:
```
{
  "fetch_data": {
    "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  "transcription_config": {
    "diarization": "speaker",
    "language": "auto",
    "operating_point": "enhanced"
  },
  "type": "transcription"
}
```

**Comment by mnemitz** [comment] 2024-10-28 11:44
Thank you for flagging this. I believe this bug was fixed in the current latest version `4.0.0`. Let us know if you encounter further issues.

**Comment by erkkimon** [comment] 2024-10-30 06:29
@mnemitz The problem occurs in v4.0.0. To me it looks like it is typed correctly but notification_config never really gets added to the payload.

**Comment by erkkimon** [comment] 2024-11-08 07:41
I double checked and it does not pass through on 4.0.0 either.

**Comment by mnemitz** [comment] 2024-11-08 10:46
@erkkimon I've confirmed this code does pass `notification_config` in v4.0.0:

```javascript
    const client = new Speechmatics("YOUR_JWT").batch
    await client.createTranscriptionJob(
      {
          "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxxx"
      },
      {
        "notification_config": [
          {
            "contents": [
              "transcript"
            ],
            "url": "https://xxxxxxxxxxxxxxxxxxxxxxxxx"
          }
        ],
        "transcription_config": {
          "language": "auto"
        },
        "type": "transcription"
      }
    )
  }
```

Ouput from network tab:

```
 {"notification_config":[{"contents":["transcript"],"url":"https://xxxxxxxxxxxxxxxxxxxxxxxxx"}],"transcription_config":{"language":"auto"},"type":"transcription","fetch_data":{"url":"https://xxxxxxxxxxxxxxxxxxxxxxxxxx"}}
```

Note the input is `{ url: ... }` as opposed to `fetch_data`. I realize this is confusing given our API structure, but this was because we chose to separate input from configuration in the SDK. The Typescript types should also reflect this.

See our original batch URL example here for reference: https://github.com/speechmatics/speechmatics-js-sdk/blob/v4.0.0/examples/example_batch_url.js

Lastly, I would recommend using our new package [`@speechmatics/batch-client`](https://www.npmjs.com/package/@speechmatics/batch-client) going forward. It should have all the functionality of `speechmatics@v4.0.0`, plus better editor integration to avoid these sorts of issues!

Going to close this issue now. Feel free to reopen/open a new issue if you encounter any problems.

**Closed by mnemitz** 2024-11-08 10:46 UTC
